#!/usr/bin/env python
#
# git-switch
#
# Switches between feature branches.
#
# Usage:
#     git switch banana
#     git switch main
#
# Is equivalent to calling:
#     git checkout <prefix>/banana
#     git checkout main
#
# If the prefixed version of the branch wasn't found, it also
# tries the name verbatim.

import sys
import os
import git
import util

if len(sys.argv) < 2:
  util.fatal('Incorrect usage, missing branch name. Use: git switch [feature]')

try:
    repo = git.Repo(os.getcwd(), search_parent_directories=True)
except git.exc.InvalidGitRepositoryError:
    util.fatal('git start must be run from within a valid git repository.')

util.fatal_if_dirty(repo)

# Try prefixed name first, then verbatim.
branch_names = (util.get_branch_name(sys.argv[1]), sys.argv[1])
for name in branch_names:
  if name in repo.heads:
    repo.heads[name].checkout()
    util.success('Switched to %s' % name)
    exit(0)

util.fatal('Branch not found. Tried: %s' % ', '.join(branch_names))
