#!/usr/bin/env python
#
# git-github-login
#
# Prompts the user to create a GitHub token; then stores their token and
# username in ~/.github-auth. (This script used to create the token, but
# as of 2/14/2020 the /authorizations endpoint is deprecated, see
# https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint/)
#
# This token can be used by other github related utility scripts.
#
# To revoke a token, visit https://github.com/settings/tokens

import getpass
import json
import os.path
import socket
import sys
import time
import requests
from requests.auth import HTTPBasicAuth
import util

username = util.prompt('GitHub username', default=getpass.getuser())
util.warn('Git Workflow needs a GitHub access token to talk to your account.')
util.warn('Create a token at https://github.com/settings/tokens/new with scope: repo')
util.warn('and enter it here.')

token = util.prompt('GitHub token (with "repo" scope)', password=True)

auth_file = util.get_auth_filename()

with open(auth_file, 'w') as outfile:
    json.dump({
        'username': username,
        'token': token,
    }, outfile)

util.success('Credentials saved to %s' % auth_file)
