#!/usr/bin/env python
#
# git-cleanup
#
# Removes all branches that are fully merged, except main and the current
# working branch.
#

import os
import git
import util
import re

current = re.compile('^\* ')

try:
  repo = git.Repo(os.getcwd(), search_parent_directories=True)
except git.exc.InvalidGitRepositoryError:
  util.fatal('git cleanup must be run from within a valid git repository.')

util.fatal_if_dirty(repo)

local_count = 0
main = util.main_branch_name(repo)
branches = repo.git.branch('--merged', main)
for line in branches.splitlines():
  branch = line.strip()
  if not current.match(branch) and branch != main:
    util.info('Removing %s' % branch)
    repo.git.branch('-d', branch)
    local_count += 1

def trim_prefix(text, prefix):
  if text.startswith(prefix):
    return text[len(prefix):]

remote_count = 0
branches = repo.git.branch('-r', '--merged', main)
for line in branches.splitlines():
  branch = trim_prefix(line.strip(), 'origin/')
  if main not in branch:
    util.info('Removing origin/%s' % branch)
    repo.git.push('--delete', 'origin', branch)
    remote_count += 1

if local_count == 0 and remote_count == 0:
  util.success('No stale branches detected')
else:
  util.success('Removed %d local and %d remote branches' % (local_count, remote_count))
